[settings]
experimental = true

[tools]
bun = "latest"
go = "latest"
node = "latest"
prettier = "latest"
python = "latest"
ruby = "latest"
rust = "latest"

[hooks.postinstall]
run = "mise exec go -- go install golang.org/x/tools/cmd/goimports@latest"
